### ISSUE TITLE
window_t.bkgd() ignore A_BOLD

### ISSUE THREAD

**Issue by askovpen** [6112/js-curses#4]
A_BOLD not work for background color. only foreground.

**Comment by 6112** [comment]
If you're talking about something like this:

```javascript
addstr("hello world", A_BOLD | A_REVERSE);
```

This is intended behaviour. In native ncurses, only the foreground color can be brighter (when it is bold text). The background colour always stays non-bright.

I *could* add an option to initscr() for that, though.

**Comment by askovpen** [comment]
thanx. don't need this option :-)
